spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: demo
    password: SecurePa55w0rd
    url: jdbc:mysql://localhost:3306/demo
  security:
    user:
      name: user
      password: password
  flyway:
    enabled: true

